{% set name = "lizard" %}
{% set version = "1.21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/terryyin/lizard/archive/refs/tags/{{ version }}.tar.gz
  sha256: da24b39793df69420c1b34d5b2c16e7b6303a0771a41ae0057c55a013191f657

build:
  entry_points:
    - lizard = lizard:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - pathspec
    - pygments
    - python >={{ python_min }}

test:
  imports:
    - lizard_ext
    - lizard_languages
  commands:
    - pip check
    - lizard --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.lizard.ws
  summary: A code analyzer without caring the C/C++ header files. It works with Java, C/C++, JavaScript, Python, Ruby, Swift, Objective C. Metrics includes cyclomatic complexity number etc.
  dev_url: https://github.com/terryyin/lizard
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - awvwgk
