{% set name = "lizard" %}
{% set version = "1.17.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/terryyin/lizard/archive/refs/tags/{{ version }}.tar.gz
  sha256: 83807f4abdd283ce474daf27f2b1045a0ceae5b3795dbaa1cf659892ebe945dc

build:
  entry_points:
    - lizard = lizard:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - pygments
    - python >={{ python_min }}

test:
  imports:
    - lizard_ext
    - lizard_languages
  commands:
    - pip check
    - lizard --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.lizard.ws
  summary: A code analyzer without caring the C/C++ header files. It works with Java, C/C++, JavaScript, Python, Ruby, Swift, Objective C. Metrics includes cyclomatic complexity number etc.
  dev_url: https://github.com/terryyin/lizard
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - awvwgk
